# See <https://rust-lang.github.io/rust-clippy/master/#await_holding_invalid_type>
# TODO: These lints don't seem to trigger, even on the example from documentation.
await-holding-invalid-types = [
    # See <https://docs.rs/tracing/latest/tracing/span/struct.Span.html#in-asynchronous-code>
    "tracing::trace::Entered",
    "tracing::trace::EnteredSpan",
]

doc-valid-idents = ["ZCash", ".."]
