# See <https://fly.io/docs/reference/configuration>

app = "kzg-ceremony-sequencer-dev"
kill_signal = "SIGINT"
kill_timeout = 30 # Seconds
processes = []

[build]
    image = "remcob/kzg-ceremony-sequencer:latest"

[[mounts]]
    source = "kzg_ceremony_sequencer_dev_data"
    destination = "/data"

[env]
    VEBOSE=3
    SERVER="http://127.0.0.1:3000/"
    DATABASE_URL="sqlite:///data/storage.sqlite"
    TRANSCRIPT_FILE="/data/transcript.json"
    TRANSCRIPT_IN_PROGRESS_FILE="/data/transcript.json.wip"

# Secrets
# - ETH_RPC_URL       (i.e. Alchemy)
# - GH_CLIENT_ID      (Register at <https://github.com/settings/applications/new>)
# - GH_CLIENT_SECRET
# - ETH_CLIENT_ID     (Register at <https://etherscan.io/myapikey>)
# - ETH_CLIENT_SECRET

[experimental]
    allowed_public_ports = []
    auto_rollback = true

[[services]]
    http_checks = []
    internal_port = 3000
    processes = ["app"]
    protocol = "tcp"
    script_checks = []

    [services.concurrency]
        hard_limit = 25
        soft_limit = 20
        type = "connections"

    [[services.ports]]
        force_https = true
        handlers = ["http"]
        port = 80

    [[services.ports]]
        handlers = ["tls", "http"]
        port = 443

    [[services.tcp_checks]]
        grace_period = "1s"
        interval = "15s"
        restart_limit = 0
        timeout = "2s"
